### PR TITLE
fix: update logo link redirect

### PR DESCRIPTION
**Pull request by hafizhpratama**

### CODE REVIEW

**Comment by vinayak25** [comment]
is this a legal attribute? I scanned through vitepress docs, but couldn't find anything.

**Comment by jeet-dhandha** [comment]
Screenshot 2024-12-19 at 10 27 56 PM


I think its valid, its included in `types` file.

**Comment by vinayak25** [comment]
could be some issue, because I was getting type error on my system. Will check it again

**Comment by vinayak25** [comment]
my bad, I was adding the attribute in the wrong context. 😮‍💨

**Comment by vinayak25** [comment]
Thanks for the contribution @hafizhpratama

**Comment by jeet-dhandha-lio** [comment]
@vinayak25 you can close this one 
- https://github.com/intentjs/intent/issues/34

**Pull request merged**
